import React, { useState } from 'react';

const FAQ = () => {
  const [openItems, setOpenItems] = useState(new Set([0])); // First item open by default

  const toggleItem = (index) => {
    const newOpenItems = new Set(openItems);
    if (openItems.has(index)) {
      newOpenItems.delete(index);
    } else {
      newOpenItems.add(index);
    }
    setOpenItems(newOpenItems);
  };

  const faqData = [
    {
      question: "How quickly can I get started with Quotely?",
      answer: "You can start using Quotely immediately after signing up. Our onboarding process takes less than 30 minutes, and you'll be generating quotes within the same day. We provide step-by-step guidance and our support team is available to help with any questions during setup."
    },
    {
      question: "What platforms and systems does Quotely integrate with?",
      answer: "Quotely features powerful built-in integrations with industry-leading platforms including TurboRater for instant multi-carrier comparative rating, Momentum AMP for comprehensive agency management, and Gail for AI-powered automation and workflow optimization. These deep integrations allow seamless data flow between systems, eliminating duplicate data entry and streamlining your entire quote-to-bind process. We're constantly expanding our partner ecosystem to provide you with the most comprehensive insurance technology stack."
    },
    {
      question: "Is there a contract or can I cancel anytime?",
      answer: "There are no long-term contracts with Quotely. All plans are month-to-month and you can cancel anytime with 30 days notice. We also offer a 14-day free trial, so you can try our platform risk-free."
    },
    {
      question: "How does Quotely protect my customer data?",
      answer: "Data security is our top priority. Quotely is SOC 2 Type II compliant and uses bank-level encryption (256-bit SSL) to protect all data in transit and at rest. We're also HIPAA compliant and regularly undergo third-party security audits. Your customer data is never shared with third parties without your explicit consent."
    },
    {
      question: "Can Quotely integrate with my existing CRM or management system?",
      answer: "Yes! Quotely offers robust API integrations with popular CRM systems like Salesforce, HubSpot, Pipedrive, and many agency management systems including Applied Epic, EZLynx, and QQCatalyst. We also provide webhook support for custom integrations. Our technical team can help you set up these integrations."
    },
    {
      question: "What kind of support do you provide?",
      answer: "We offer comprehensive support across all plans. Starter plan includes email support with 24-hour response time. Professional plan adds priority support with same-day response. Enterprise customers get dedicated account management and 24/7 phone support. We also provide extensive documentation, video tutorials, and live training sessions."
    },
    {
      question: "How accurate are the quotes generated by Quotely?",
      answer: "Quotely generates quotes with 99.2% accuracy by connecting directly to carrier rating engines and using real-time data. Our quotes are the same as what you'd get directly from the carrier. We continuously monitor and update our algorithms to ensure accuracy, and any discrepancies are immediately addressed."
    },
    {
      question: "Can I customize the quote forms and branding?",
      answer: "Absolutely! Quotely offers extensive customization options. You can add your agency logo, customize colors and fonts to match your brand, modify quote forms to collect the information you need, and even white-label the entire experience. Professional and Enterprise plans include advanced branding and customization features."
    },
    {
      question: "What happens to my data if I decide to leave Quotely?",
      answer: "You own your data 100%. If you decide to cancel your Quotely subscription, you can export all your customer data, quotes, and reports in standard formats (CSV, PDF, API). We provide a 90-day grace period after cancellation to download your data, and our team will assist with the export process to ensure a smooth transition."
    },
    {
      question: "Does Quotely work on mobile devices?",
      answer: "Yes! Quotely is fully responsive and works seamlessly on all devices - desktop, tablet, and mobile. We also offer native iOS and Android apps for agents who prefer mobile-first workflows. All features are available across all platforms, so you can generate quotes and manage your business from anywhere."
    }
  ];

  return (
    <section style={styles.faq}>
      <div style={styles.container}>
        <div style={styles.header}>
          <h2 style={styles.title}>Frequently Asked Questions</h2>
          <p style={styles.subtitle}>
            Get answers to the most common questions about Quotely. 
            Can't find what you're looking for? Contact our support team.
          </p>
        </div>

        <div style={styles.faqContainer}>
          <div style={styles.faqList}>
            {faqData.map((item, index) => (
              <div 
                key={index} 
                style={{
                  ...styles.faqItem,
                  ...(openItems.has(index) ? styles.faqItemOpen : {})
                }}
              >
                <button
                  style={styles.faqQuestion}
                  onClick={() => toggleItem(index)}
                  aria-expanded={openItems.has(index)}
                >
                  <span style={styles.questionText}>{item.question}</span>
                  <span 
                    style={{
                      ...styles.expandIcon,
                      ...(openItems.has(index) ? styles.expandIconOpen : {})
                    }}
                  >
                    +
                  </span>
                </button>
                
                <div 
                  style={{
                    ...styles.faqAnswer,
                    ...(openItems.has(index) ? styles.faqAnswerOpen : {})
                  }}
                >
                  <div style={styles.answerContent}>
                    <p style={styles.answerText}>{item.answer}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div style={styles.contactCard}>
            <div style={styles.contactIcon}>💬</div>
            <h3 style={styles.contactTitle}>Still have questions?</h3>
            <p style={styles.contactDescription}>
              Our support team is here to help you get the most out of Quotely. 
              Reach out anytime for personalized assistance.
            </p>
            <div style={styles.contactButtons}>
              <a 
                href="/contact" 
                style={styles.contactButton}
                onMouseEnter={(e) => {
                  e.target.style.backgroundColor = styles.contactButtonHover.backgroundColor;
                  e.target.style.transform = styles.contactButtonHover.transform;
                }}
                onMouseLeave={(e) => {
                  e.target.style.backgroundColor = styles.contactButton.backgroundColor;
                  e.target.style.transform = 'translateY(0)';
                }}
              >
                Contact Support
              </a>
              <a 
                href="/demo" 
                style={styles.demoButton}
                onMouseEnter={(e) => {
                  e.target.style.backgroundColor = styles.demoButtonHover.backgroundColor;
                  e.target.style.borderColor = styles.demoButtonHover.borderColor;
                }}
                onMouseLeave={(e) => {
                  e.target.style.backgroundColor = styles.demoButton.backgroundColor;
                  e.target.style.borderColor = styles.demoButton.borderColor;
                }}
              >
                Schedule Demo
              </a>
            </div>
          </div>
        </div>

        <div style={styles.additionalResources}>
          <h3 style={styles.resourcesTitle}>Additional Resources</h3>
          <div style={styles.resourcesGrid}>
            <div style={styles.resourceCard}>
              <div style={styles.resourceIcon}>📚</div>
              <h4 style={styles.resourceCardTitle}>Knowledge Base</h4>
              <p style={styles.resourceCardDescription}>
                Comprehensive guides and tutorials to help you master Quotely
              </p>
              <a href="/help" style={styles.resourceLink}>Browse Articles →</a>
            </div>
            
            <div style={styles.resourceCard}>
              <div style={styles.resourceIcon}>🎥</div>
              <h4 style={styles.resourceCardTitle}>Video Tutorials</h4>
              <p style={styles.resourceCardDescription}>
                Step-by-step video guides for all Quotely features
              </p>
              <a href="/tutorials" style={styles.resourceLink}>Watch Videos →</a>
            </div>
            
            <div style={styles.resourceCard}>
              <div style={styles.resourceIcon}>👥</div>
              <h4 style={styles.resourceCardTitle}>Community Forum</h4>
              <p style={styles.resourceCardDescription}>
                Connect with other agents and share best practices
              </p>
              <a href="/community" style={styles.resourceLink}>Join Community →</a>
            </div>
            
            <div style={styles.resourceCard}>
              <div style={styles.resourceIcon}>📞</div>
              <h4 style={styles.resourceCardTitle}>Live Training</h4>
              <p style={styles.resourceCardDescription}>
                Join our weekly training sessions and Q&A calls
              </p>
              <a href="/training" style={styles.resourceLink}>Register Now →</a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const styles = {
  faq: {
    padding: '120px 0',
    backgroundColor: 'white'
  },
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '0 20px'
  },
  header: {
    textAlign: 'center',
    marginBottom: '80px'
  },
  title: {
    fontSize: 'clamp(2rem, 4vw, 3rem)',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '16px'
  },
  subtitle: {
    fontSize: '1.2rem',
    color: '#64748b',
    maxWidth: '600px',
    margin: '0 auto'
  },
  faqContainer: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '60px',
    marginBottom: '80px',
    '@media (max-width: 968px)': {
      gridTemplateColumns: '1fr',
      gap: '40px'
    }
  },
  faqList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px'
  },
  faqItem: {
    backgroundColor: 'white',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    overflow: 'hidden',
    transition: 'all 0.2s ease'
  },
  faqItemOpen: {
    borderColor: '#2563eb',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.1)'
  },
  faqQuestion: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '24px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background-color 0.2s ease'
  },
  questionText: {
    fontSize: '1.1rem',
    fontWeight: '600',
    color: '#1e293b',
    lineHeight: '1.4',
    paddingRight: '16px'
  },
  expandIcon: {
    fontSize: '1.5rem',
    fontWeight: '300',
    color: '#64748b',
    transition: 'transform 0.2s ease',
    flexShrink: 0
  },
  expandIconOpen: {
    transform: 'rotate(45deg)'
  },
  faqAnswer: {
    maxHeight: '0',
    overflow: 'hidden',
    transition: 'max-height 0.3s ease, padding 0.3s ease'
  },
  faqAnswerOpen: {
    maxHeight: '1000px',
    borderTop: '1px solid #f1f5f9'
  },
  answerContent: {
    padding: '0 24px 24px'
  },
  answerText: {
    fontSize: '1rem',
    color: '#4b5563',
    lineHeight: '1.6',
    margin: 0,
    paddingTop: '16px'
  },
  contactCard: {
    backgroundColor: '#f8fafc',
    borderRadius: '16px',
    padding: '32px',
    textAlign: 'center',
    border: '1px solid #e2e8f0',
    height: 'fit-content',
    position: 'sticky',
    top: '100px'
  },
  contactIcon: {
    fontSize: '3rem',
    marginBottom: '16px'
  },
  contactTitle: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '12px'
  },
  contactDescription: {
    fontSize: '1rem',
    color: '#64748b',
    lineHeight: '1.5',
    marginBottom: '24px'
  },
  contactButtons: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px'
  },
  contactButton: {
    backgroundColor: '#2563eb',
    color: 'white',
    padding: '14px 24px',
    borderRadius: '8px',
    textDecoration: 'none',
    fontSize: '1rem',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    display: 'inline-block'
  },
  contactButtonHover: {
    backgroundColor: '#1d4ed8',
    transform: 'translateY(-1px)'
  },
  demoButton: {
    backgroundColor: 'transparent',
    color: '#2563eb',
    padding: '14px 24px',
    borderRadius: '8px',
    textDecoration: 'none',
    fontSize: '1rem',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    border: '2px solid #e2e8f0',
    display: 'inline-block'
  },
  demoButtonHover: {
    backgroundColor: '#f1f5f9',
    borderColor: '#2563eb'
  },
  additionalResources: {
    borderTop: '1px solid #e2e8f0',
    paddingTop: '60px'
  },
  resourcesTitle: {
    fontSize: '2rem',
    fontWeight: '700',
    color: '#1e293b',
    textAlign: 'center',
    marginBottom: '40px'
  },
  resourcesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '24px'
  },
  resourceCard: {
    backgroundColor: 'white',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    padding: '24px',
    textAlign: 'center',
    transition: 'all 0.2s ease'
  },
  resourceIcon: {
    fontSize: '2.5rem',
    marginBottom: '16px'
  },
  resourceCardTitle: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: '12px'
  },
  resourceCardDescription: {
    fontSize: '0.95rem',
    color: '#64748b',
    lineHeight: '1.5',
    marginBottom: '16px'
  },
  resourceLink: {
    color: '#2563eb',
    textDecoration: 'none',
    fontSize: '0.95rem',
    fontWeight: '600',
    transition: 'color 0.2s ease'
  }
};

export default FAQ;